---
- name: Test the template
  hosts: localhost
  gather_facts: false
  vars:

  tasks:
    - name: pause with render
      pause:
        prompt:  "{{ lookup('template', '{{ item }}') }}"
      loop: "{{ lookup('fileglob', 'templates/*.j2', wantlist=True ) }}"

- name: Test the vars
  hosts: all

  tasks:
    - debug:
        var: {{ test_var }}"
      ignore_errors: yes      
